#!/usr/bin/env bash
# Shared Infisical path + secret names for iOS signing sync/restore.
# shellcheck disable=SC2034

IOS_SIGNING_INFISICAL_ENV="${IOS_SIGNING_INFISICAL_ENV:-prod}"
IOS_SIGNING_INFISICAL_PATH="${IOS_SIGNING_INFISICAL_PATH:-/ios-signing}"

IOS_SIGNING_SECRET_P12_BASE64="IOS_DISTRIBUTION_CERT_P12_BASE64"
IOS_SIGNING_SECRET_P12_PASSWORD="IOS_DISTRIBUTION_CERT_PASSWORD"
IOS_SIGNING_SECRET_CERT_SERIAL="IOS_DISTRIBUTION_CERT_SERIAL"
IOS_SIGNING_SECRET_PROFILE_BASE64="IOS_PROVISIONING_PROFILE_BASE64"
IOS_SIGNING_SECRET_TEAM_ID="IOS_APPLE_TEAM_ID"
IOS_SIGNING_SECRET_BUNDLE_ID="IOS_BUNDLE_IDENTIFIER"
IOS_SIGNING_SECRET_CERT_CN="IOS_DISTRIBUTION_CERT_COMMON_NAME"
